### What is NumPy?
NumPy stands for Numerical Python.
* It is an open-source library used for numerical computing.
* It is widely used in data science, machine learning, artificial intelligence,
  and scientific computing due to its speed, efficiency, flexibility, and powerful functionality
  as compared to Python lists.

### Applications of NumPy:
   * Data science and machine learning 
   * Image processing 
   * Linear algebra 
   * Game development 
   * Statistics and probability 
   * Signal processing 
   * Engineering

### Why Use NumPy ? ###
* Faster 
* Memory Efficient 
* Convenient 

### Section Goals
 1.Basic of Numpy \
 2.creating Numpy Arrys \
 3.Indexing and selection on Arrys \
 4.Universal Function \
 5.Slicing in Numpy Array \
 6.General Opreation \
 7.Exercises 

### Installation
Install NumPy using pip:

In [5]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
Mylist_1 = [1,2,3,4,5,6]

In [4]:
Mylist_2 = [7,8,9,10,11,10]

In [5]:
Mylist_1 + Mylist_2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 10]

In [6]:
result_list=[]
for first , sec in zip( Mylist_1, Mylist_2 ):
    result_list.append(first + sec)
result_list

[8, 10, 12, 14, 16, 16]

In [7]:
type(result_list)

list

##### Import NumPy in notebook

In [9]:
import numpy as np #use NumPy functionality as np prefix

In [10]:
Array_1 = np.array([0,1,2,3,4,5,6])

In [11]:
Array_2 = np.array([8,9,10,4,5,6,7])

In [12]:
Array_1 + Array_2  #vectorizd operation

array([ 8, 10, 12,  7,  9, 11, 13])

In [13]:
type(Array_1)

numpy.ndarray

In [14]:
Array_int = np.array([1,3,4,6,8,2,5])

In [15]:
Array_int

array([1, 3, 4, 6, 8, 2, 5])

In [16]:
Array_int.dtype

dtype('int32')

In [17]:
Array_f = np.array([1,2.0,3.7,4,5,6,7])

In [18]:
Array_f

array([1. , 2. , 3.7, 4. , 5. , 6. , 7. ])

In [19]:
Array_f.dtype

dtype('float64')

In [20]:
print(Array_int)
print(Array_f)

[1 3 4 6 8 2 5]
[1.  2.  3.7 4.  5.  6.  7. ]


In [21]:
Array_int +  Array_f     #vectorizd operation

array([ 2. ,  5. ,  7.7, 10. , 13. ,  8. , 12. ])

In [22]:
#converting int to float or float to integer

In [23]:
Array_int[0]

1

In [24]:
Array_int[0]= 0.5   #assign to decimal

In [55]:
Array_int

array([0, 3, 4, 6, 8, 2, 5])

In [32]:
Array_f[0]

6.0

In [31]:
Array_f[0]= 6 #assign to integer

In [28]:
Array_f #In Array alwasy be same datatype 

array([6. , 2. , 3.7, 4. , 5. , 6. , 7. ])

In [54]:
list_1=[0.5,0.2,1,2,3,5,6]
list_1

[0.5, 0.2, 1, 2, 3, 5, 6]

In [29]:
#broadcast 

In [238]:
Array_int = np.array([1,3,4,6,8,2,5])

In [264]:
Array_int.shape

(7,)

In [241]:
Array_int = np.array([2,5.0,3.7,4,5,6.1,7,2])

In [242]:
Array_f.shape

(8,)

In [33]:
Array_int.ndim

1

In [243]:
Array_int + Array_f

ValueError: operands could not be broadcast together with shapes (7,) (8,) 

In [251]:
Array_int.size

7

In [252]:
Array_f.size

8

In [40]:
Mylist_1 =[0,1,2,3,4,5]
Mylist_2 = [6,7,8,8,9,10,11,12,13]

In [41]:
len(Mylist_1)  

6

In [42]:
len(Mylist_2)

9

In [43]:
 Mylist_1 + Mylist_2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 8, 9, 10, 11, 12, 13]

In [ ]:
#vectorizd operation

In [287]:
Array = np.array([1,2,3,4,5,6,7,8])

In [288]:
Array * 10

array([10, 20, 30, 40, 50, 60, 70, 80])

In [289]:
Array / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [290]:
Array**2

array([ 1,  4,  9, 16, 25, 36, 49, 64], dtype=int32)

In [49]:
list_1=[1,2.4,35.6,4,5,6] #not possibile vect operation 
list_1 * 2 

[1, 2.4, 35.6, 4, 5, 6, 1, 2.4, 35.6, 4, 5, 6]

In [50]:
list_1 / 2 #cannot do math operation in list 

TypeError: unsupported operand type(s) for /: 'list' and 'int'

### Universal Functions (ufunc) in NumPy
 A universal function (ufunc) in NumPy is a function that
performs element-wise operations on arrays.

#### A. Arithmetic Functions

In [296]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [297]:
np.add(a, b)

array([5, 7, 9])

In [314]:
a = [1, 2, 3]
b = [4, 5, 6]

result = [x + y for x, y in zip(a, b)]  #using list comprehension 


In [315]:
result 

[6, 8, 10, 12]

In [ ]:
result_1=[]
for i , j in zip(a,b):
    reslut.append()

In [298]:
np.subtract(a, b)

array([-3, -3, -3])

In [299]:
np.multiply(a, b)

array([ 4, 10, 18])

In [300]:
np.divide(b, a)

array([4. , 2.5, 2. ])

#### B. Trigonometric Functions

In [301]:
angles = np.array([0, np.pi/2, np.pi])

In [302]:
np.sin(angles)

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [320]:
#if using normal python 

pi = 3.14159265359
angles = [0, pi/2, pi] 

def sine_approx(x):
    return x - (x**3 / 6) + (x**5 / 120)  

sin_values = []
for angle in angles:
    sin_values.append(sine_approx(angle))

In [321]:
sin_values  

[0.0, 1.0045248555348194, 0.5240439134171941]

In [303]:
np.cos(angles)

array([ 1.000000e+00,  6.123234e-17, -1.000000e+00])

In [304]:
np.tan(angles)

array([ 0.00000000e+00,  1.63312394e+16, -1.22464680e-16])

#### C. Exponential and Logarithmic Functions

In [307]:
x = np.array([0 , 1, 2, 3])

In [308]:
np.exp(x)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

#### D. Statistical Functions

In [309]:
data = np.array([1, 2, 3, 4, 5])

In [310]:
np.mean(data)

3.0

In [311]:
np.median(data)

3.0

In [313]:
np.std(data)

1.4142135623730951

#### E. Comparison Functions

In [322]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [323]:
np.greater(x, y)

array([False, False,  True])

In [324]:
np.less(x, y)

array([ True, False, False])

In [325]:
np.equal(x,y)

array([False,  True, False])

#### Slicing in NumPy Array

In [1]:
from IPython.display import display, Image

display(Image(filename="Array.png" , width=400, height=200 )) 


In [386]:
Array=np.array([0,10,20,30,40,50,60,70,80])

In [364]:
Array[1:3]

array([10, 20])

In [365]:
Array[:-3]

array([ 0, 10, 20, 30, 40, 50])

In [366]:
Array[1:-1]

array([10, 20, 30, 40, 50, 60, 70])

In [367]:
Array[1:]

array([10, 20, 30, 40, 50, 60, 70, 80])

In [368]:
Array[:3]

array([ 0, 10, 20])

In [370]:
Array[::2]

array([ 0, 20, 40, 60, 80])

In [371]:
Array[0]

0

In [383]:
Array[2:4]

array([100, 100])

In [387]:
slice_of_arr=Array[0:5]

In [388]:
slice_of_arr

array([ 0, 10, 20, 30, 40])

In [389]:
slice_of_arr[:]=100

In [390]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [80]:
# SLICING IN 2D ARRAY

In [391]:
c=np.array([[0,1,2,3],[5,6,7,8]])

In [392]:
c

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [395]:
c.shape #shape =( row ,columns)

(2, 4)

In [397]:
c[1] #2 row

array([5, 6, 7, 8])

In [398]:
c[0]

array([0, 1, 2, 3])

In [403]:
c[:,:]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [404]:
c.ndim

2

In [406]:
c[1,3]

8

In [407]:
c[1,3]=10

In [410]:
c[1,3]

10

In [412]:
c

array([[ 0,  1,  2,  3],
       [ 5,  6,  7, 10]])

In [413]:
c[0,2:4]

array([2, 3])

#### Converting list into NumPy Array

In [414]:
mylist=[1,3,5,6]
mylist

[1, 3, 5, 6]

In [415]:
type(mylist)

list

In [416]:
mylist*2

[1, 3, 5, 6, 1, 3, 5, 6]

In [417]:
arr=np.array(mylist)

In [418]:
arr

array([1, 3, 5, 6])

In [419]:
type(arr)

numpy.ndarray

In [420]:
mylist=[[1,3,5],[4,5,6],[1,4,76],[1,3,5]]
mylist

[[1, 3, 5], [4, 5, 6], [1, 4, 76], [1, 3, 5]]

In [421]:
np.array(mylist)

array([[ 1,  3,  5],
       [ 4,  5,  6],
       [ 1,  4, 76],
       [ 1,  3,  5]])

In [422]:
mymatrix=np.array(mylist)

In [423]:
mymatrix.shape

(4, 3)

In [424]:
mymatrix.ndim

2

#### NumPy Function 

In [116]:
np.arange(0,15) #start stop and step

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [117]:
#the start is incluse and the end is exlusve 

In [118]:
np.arange(0,10,2) #step size parameter by deflut step size is 1

array([0, 2, 4, 6, 8])

In [119]:
np.zeros(5) #1d arrays 

array([0., 0., 0., 0., 0.])

In [120]:
np.zeros((4,10)) # we can also pass tuple 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [121]:
np.ones((5,5)) +5

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [122]:
np.ones(4)*100

array([100., 100., 100., 100.])

In [123]:
np.ones(4)/100

array([0.01, 0.01, 0.01, 0.01])

In [127]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [129]:
np.random.rand(1) #random arrays

array([0.74824067])

In [437]:
np.random.rand(3,5)

array([[0.80672348, 0.68028858, 0.82199911, 0.25732462, 0.27368519],
       [0.55318064, 0.66184615, 0.18501196, 0.12935376, 0.81079049],
       [0.90679406, 0.8044611 , 0.07703078, 0.27789765, 0.55596778]])

In [133]:
np.random.randint(1,100,5)

array([67,  7, 50, 83, 86])

In [138]:
arr.shape

(25,)

In [431]:
arr1=np.random.randint(0,50,16)

In [432]:
arr1.shape

(16,)

In [433]:
arr1.reshape(4,4)

array([[14,  1,  4, 42],
       [36, 15, 36,  8],
       [ 2, 49, 19, 13],
       [22, 34, 44, 41]])

In [352]:
arr1.max()

48

In [353]:
arr1.ndim

1

In [143]:
arr1.min()

8

In [144]:
arr1

array([26, 45,  9, 14, 11,  8, 48, 33,  8, 42, 10, 36, 44, 23, 33, 13])

In [146]:
arr1.argmin()

5

In [147]:
arr1.argmax()

6

In [148]:
arr1.dtype

dtype('int32')

In [166]:
np.sqrt(arr1)

array([5.09901951, 6.70820393, 3.        , 3.74165739, 3.31662479,
       2.82842712, 6.92820323, 5.74456265, 2.82842712, 6.4807407 ,
       3.16227766, 6.        , 6.63324958, 4.79583152, 5.74456265,
       3.60555128])

In [167]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [169]:
arr1.sum()

403

### Numpy exericses 

##### import numpy library 

#### create an array of 10 zeros

#### create an array of 10 ones

#### create an array of 10 fives 

#### craete an array of  integer  from 10 to 50

#### create an array of all even integer from 10 to 50

#### create 3x3 matrix with the values ranging of 0 to 8

#### create 3x3 identity matrix

#### create an arry of 20 linearly spaced point b/w 0 and 1